spring.application.name=dream-shops

server.port = 9193

spring.datasource.url =jdbc:mysql://localhost:3306/dream_shops_db
spring.datasource.username = root
spring.datasource.password= sqlWES54-23

##This tells Spring Boot which JDBC driver to use to connect to your database.
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

## This tells Hibernate (the JPA implementation) which SQL language style to use.
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

##This tells Spring Boot to print SQL queries to the console.
spring.jpa.show-sql = true

## This tells Spring Boot to print SQL queries to the console.
show.jpa.properties.hibernate.format_sql = true

##(Create, update, create-drop, validate)
spring.jpa.hibernate.ddl-auto = update